#!/bin/sh
#
# sysmon:   Starts the sysmon daemon
#
# chkconfig: 2345 97 03
# processname: sysmon

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

# See how we were called.
case "$1" in
  start)
	echo -n "Starting sysmon daemon: "
	daemon systemmonitor
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/sysmon
	;;
  stop)
	echo -n "Stopping sysmon daemon: "
	killproc systemmonitor
	RETVAL=$?
	rm -f /var/lock/subsys/systemmonitor && rm -f /var/lock/systemmonitor
        echo
	;;
  status)
	status systemmonitor
	RETVAL=$?
	;;
  restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL

