#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2001 e-smith, inc.
#		
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from e-smith, inc.
# For details, please visit our web site at www.e-smith.com or
# call us on 1 888 ESMITH 1 (US/Canada toll free) or +1 613 564 8000
#----------------------------------------------------------------------

package esmith;

use strict;
use Errno;
use esmith::config;
use esmith::util;
use esmith::db;

my %conf;
tie %conf, 'esmith::config';

#--------------------------------------------------------------
# First, check to see if the service has been enabled in the
# services database.  If not, default to enabling it.
#--------------------------------------------------------------

symlink("/etc/rc.d/init.d/e-smith-service","/etc/rc.d/rc7.d/S97systemmonitor") unless(-e "/etc/rc.d/rc7.d/S97systemmonitor");

my $serviceName   = "systemmonitor";

my $serviceStatus = db_get_prop(\%conf, $serviceName, "status");
db_set(\%conf, $serviceName, "service", { status => "enabled" }) unless (defined $serviceStatus);

exit (0);
